"""import turtle
window = turtle.Screen()

pragya_turtle = turtle.Turtle()
rishabh_turtle = turtle.Turtle()
def square():

    rishabh_turtle.forward(100)
    rishabh_turtle.right(90)
    rishabh_turtle.forward(100)
    rishabh_turtle.right(90)
    rishabh_turtle.forward(100)
    rishabh_turtle.right(90)
    rishabh_turtle.forward(100)

def circle():

    for i in range(10,100,5):
        pragya_turtle.circle(i,45)
        

circle()
square()
   
    

window.exitonclick()"""
import turtle
window = turtle.Screen()
art_turtle = turtle.Turtle()

art_turtle.forward (100)
art_turtle.right (90)
art_turtle.forward (100)
art_turtle.right (90)
art_turtle.forward (90)
art_turtle.right (90)
art_turtle.forward (90)
art_turtle.right (90)
art_turtle.forward (80)
art_turtle.right (90)
art_turtle.forward (80)
art_turtle.right (90)
art_turtle.forward (70)
art_turtle.right (90)
art_turtle.forward (70)
art_turtle.right (90)
art_turtle.forward (60)
art_turtle.right (90)
art_turtle.forward (60)
art_turtle.right (90)
art_turtle.forward (50)
art_turtle.right (90)
art_turtle.forward (50)
art_turtle.right (90)
art_turtle.forward (40)
art_turtle.right (90)
art_turtle.forward (40)
art_turtle.right (90)
art_turtle.forward (30)
art_turtle.right (90)
art_turtle.forward (30)
art_turtle.right (90)
art_turtle.forward (20)
art_turtle.right (90)
art_turtle.forward (20)
art_turtle.right (90)
art_turtle.forward (10)
art_turtle.right (90)
art_turtle.forward (10)
art_turtle.right (90)


  """art_turtle.forward (10)
  art_turtle.right (90)
  art_turtle.forward (10)
  art_turtle.right (90)
  art_turtle.forward (20)
  art_turtle.right (90)
  art_turtle.forward (20)
  art_turtle.right (90)
  art_turtle.forward (30)
  art_turtle.right (90)
  art_turtle.forward (30)
  art_turtle.right (90)
  art_turtle.forward (40)
  art_turtle.right (90)
  art_turtle.forward (40)
  art_turtle.right (90)
  art_turtle.forward (50)
  art_turtle.right (90)
  art_turtle.forward (50)
  art_turtle.right (90)
  art_turtle.forward (60)
  art_turtle.right (90)
  art_turtle.forward (60)
  art_turtle.right (90)
  art_turtle.forward (70)
  art_turtle.right (90)
  art_turtle.forward (70)
  art_turtle.right (90)
  art_turtle.forward (80)
  art_turtle.right (90)
  art_turtle.forward (80)
  art_turtle.right (90)
  art_turtle.forward (90)
  art_turtle.right (90)
  art_turtle.forward (90)
  art_turtle.right (90)
  art_turtle.forward (100)
  art_turtle.right (90)
  art_turtle.forward (200)
  art_turtle.left (90)
  art_turtle.forward (100)
  art_turtle.left (90)
  art_turtle.forward (100)
  art_turtle.left (90)
  art_turtle.forward (90)
  art_turtle.left (90)
  art_turtle.forward (90)
  art_turtle.left (90)
  art_turtle.forward (80)
  art_turtle.left (90)
  art_turtle.forward (80)
  art_turtle.left (90)
  art_turtle.forward (70)
  art_turtle.left(90)
  art_turtle.forward (70)
  art_turtle.left(90)
  art_turtle.forward (60)
  art_turtle.left (90)
  art_turtle.forward (60)
  art_turtle.left (90)
  art_turtle.forward (50)
  art_turtle.left (90)
  art_turtle.forward (50)
  art_turtle.left (90)
  art_turtle.forward (40)
  art_turtle.left (90)
  art_turtle.forward (40)
  art_turtle.left (90)
  art_turtle.forward (30)
  art_turtle.left (90)
  art_turtle.forward (30)
  art_turtle.left (90)
  art_turtle.forward (20)
  art_turtle.left (90)
  art_turtle.forward (20)
  art_turtle.left (90)
  art_turtle.forward (10)
  art_turtle.left (90)
  art_turtle.forward (10)
  art_turtle.left(90)"""
window.exitonclick()
